### ISSUE TITLE
Make synchronized files easier to recognize

### ISSUE THREAD

**Issue by kyntk** [ryokat3/qiita-sync#58]
Thank you so much for creating such a wonderful and useful tool!

## What

Make synchronized files easier to recognize. 

## Why

When synchronizing for the first time, a lot number of articles will be imported who have already written many articles, however the id is not readable and understandable by people.

## Suggestion

Add created date to the head of the file.
e.g. `20220120_d054b95f68810f70b136.md`

**Comment by ryokat3** [comment]
Hi kyntk,
thank you for your suggestion!
I think it's a great idea and I would like to implement your idea in future release.
I will come back to you when it gets ready.

**Comment by kyntk** [comment]
Thank you so much for your very quick response and implementation!
